apiVersion: v1
kind: Namespace
metadata:
  name: telnet-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telnet-server
  namespace: telnet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telnet-server
  template:
    metadata:
      labels:
        app: telnet-server
    spec:
      containers:
      - name: telnet
        image: ghcr.io/lgiuliani80/trivial-tcp-server:master-8794151
        ports:
        - name: telnet
          containerPort: 2323
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: telnet-loadbalancer
  namespace: telnet-service
  labels:
    app: telnet-server
spec:
  type: LoadBalancer
  ports:
  - name: telnet
    port: 2323
    targetPort: 2323
    protocol: TCP
  selector:
    app: telnet-server
  sessionAffinity: ClientIP
